### ISSUE TITLE
Add a meaningful README.md

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/observable#17]

**Comment by mohamedhayibor** [comment]
Will gladly work on this. At the top of your head, what structure are you thinking of?  @matanlurey

**Comment by matanlurey** [comment]
@mohamedhayibor I was considering the following points:

- A bit about the origins (from `Object.observe`/ES proposal that was dropped)
- Observable collections are mutable - don't need to change APIs to support immutable
- Observable collections allow optimizations for read heavy/write light applications
    - Give an example of a large UI table with 1000+ rows, where 1 row is edited at a time

Also introduce the `Differ` class, and `<List|Map|Set>Differ` which can be used to get change records between two non-observable collections - nice for re-using API or using in your own client library.

Let me know if you're interested. Start with a small-ish PR so we can iterate.

**Comment by mohamedhayibor** [comment]
Awesome. I'll take a crack at it. Thanks for the guidance.
