### ISSUE TITLE
Dev branch is required to use pkg/observable

### ISSUE THREAD

**Issue by mohamedhayibor** [dart-lang/observable#19]
```
$ pub get
Resolving dependencies... (3.1s)
Package collection has no versions that match >=1.11.0 <2.0.0 derived from:
- observable depends on version ^1.11.0
```
verbose version:  https://gist.github.com/mohamedhayibor/11feae8084e18db0a04b3fe638d35c85

**Comment by mohamedhayibor** [comment]
Seems like it started failing at commit: 010bcd70f2f5bfc840601921baf8c26befcbde1d

**Comment by mohamedhayibor** [comment]
I think the issue is coming from the package `observable`, when I tried `pub get` on it, the ouput is:
```
Resolving dependencies... (1.3s)
Package collection requires SDK version >=1.21.0-dev.1.0 <2.0.0 but the current SDK is 1.20.1.
```
It is funny because removing `collection` from this repo's pubspec, the installation works as expected and all tests pass.

I will try upgrading my sdk.

**Comment by matanlurey** [comment]
A dev branch is currently required to use this package. 

I'm expecting stable to catch up soon, and then this will be more usable.
