### ISSUE TITLE
ListChangeRecord.added gives incorrect results

### ISSUE THREAD

**Issue by buhhy** [dart-lang/observable#36]
Looking at the source for ListChangeRecord:

http://google3/third_party/dart/observable/lib/src/records/list_change_record.dart?l=69&rcl=139922884

The 'added' method uses object.getRange(index, addedCount), which is incorrect because getRange takes a start index and end index. The result is a thrown error if index > addedCount. Correct logic should probably be object.getRange(index, index + addedCount).

**Comment by matanlurey** [comment]
Thanks!

**Comment by matanlurey** [comment]
This change was reverted I believe.
