### ISSUE TITLE
Dart 2 runtime errors in tests

### ISSUE THREAD

**Issue by keertip** [dart-lang/observable#67]
running tests in dart 2 mode,

type 'SubListIterable<String>' is not a subtype of type 'Iterable<Null>' of 'iterable' where...
type 'SubListIterable<String>' is not a subtype of type 'Iterable<Null>' of 'iterable' where
  SubListIterable is from dart:_internal
  String is from dart:core
  Iterable is from dart:core
  Null is from dart:core
dart:core                                                                               List.insertAll
../../observable/lib/src/differs/list_differ.dart 366:19  _mergeSplices
../../observable/lib/src/differs/list_differ.dart 423:5   _createInitialSplices
../../tobservable/lib/src/differs/list_differ.dart 448:26  projectListSplices
package:observable/src/observable_list.dart 335:21                                      ObservableList.deliverListChanges
===== asynchronous gap ===========================
dart:async                                                                              scheduleMicrotask
package:observable/src/observable_list.dart 312:7                                       ObservableList._notifyListChange
package:observable/src/observable_list.dart 233:7                                       ObservableList.removeRange
../../observable/test/list_change_test.dart 134:13        listChangeTests.<fn>.<fn>

**Comment by nshahan** [comment]
I'm testing a fix internally.
