### ISSUE TITLE
Please update to support dart 2.9.0-5.0.dev

### ISSUE THREAD

**Issue by insinfo** [dart-lang/observable#94]
Please update to support dart 2.9.0-5.0.dev

due to this https://github.com/dart-lang/angular/issues/1891
  problem I had to upgrade to dart 2.9 Angular 6 is working correctly without angular_components
Due to this

Because observable> = 0.1.1 <= 0.22.1 + 3 requires SDK version <2.0.0 or> = 2.0.0-dev.23.0 <2.0.0 and angular_components> = 0.9.0-beta + 1 <0.13.0 depends on observable ^ 0.22.1 + 3, angular_components> = 0.9.0-beta + 1 <0.13.0 requires observable ^ 0.22.1 + 4.
And because angular_components <0.9.0-beta + 1 requires SDK version> = 1.22.0 <2.0.0-∞, angular_components <0.13.0 requires observable ^ 0.22.1 + 4.
And because angular_components> = 0.13.0 depends on observable ^ 0.22.2 which depends on dart_internal ^ 0.1.1, every version of angular_components requires dart_internal ^ 0.1.1.
So, because dart_internal> = 0.1.1 requires SDK version> = 2.0.0-dev.12.0 <2.9.0 and angular_form_bug depends on angular_components any, version solving failed.

**Comment by markegli** [comment]
Hi @insinfo,

I'm sorry to see you're in a bit of bind with dependencies. The Observable library depends on dart_internal, which currently requires Dart < 2.9.0. It is infeasible for us to remove this dependency, so unfortunately we cannot support Dart 2.9.0-5.0.dev.

From the latest comment on dart-lang/angular#1891, it sounds like 2.8.0-20.11.beta and 2.8.0-dev.20.7 have the fix, so you could try those, and hopefully 2.8.1 will land soon.
